# https://github.com/atom/ci

language: generic

os:
  - linux
  - osx

install:
  - |
    if [ "$TRAVIS_OS_NAME" = 'linux' ]; then
      # Build Csound.
      sudo apt-get --assume-yes install libsndfile1-dev
      wget https://github.com/csound/csound/archive/6.13.0.tar.gz
      tar -xf 6.13.0.tar.gz
      mkdir csound
      cd csound
      # When built with DSSI <http://dssi.sourceforge.net> opcodes, attempting
      # to produce sound from Csound 6.10.0 and later on Travis CI results in a
      # segmentation fault (see https://github.com/csound/csound/issues/901).
      cmake -DBUILD_DSSI_OPCODES=NO ../csound-6.13.0
      make
      sudo make install
      sudo ldconfig
      cd ..
      # Get csound-api dependencies.
      sudo apt-get --assume-yes install libboost-dev
    else
      brew install csound
    fi

script: curl --silent https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh
