# https://github.com/atom/ci

install:
  - set CL=/I"C:\Libraries\boost_1_69_0"

build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

skip_tags: true
test: off
